name: damage_detection
channels:
  - conda-forge
dependencies:
  - numpy
  - geopandas
  - pandas
  - rasterio
  - rioxarray
  - pytorch
  - sklearn
  - matplotlib
  - tqdm
  - skimage
  - leafmap
  - pydantic
  - python-dotenv
  - black
  - opencv
  - arosics[version='>=1.3.0']
  - osmnx
  - albumentations
  - segmentation-models-pytorch=0.1.3
  - torchinfo
  - h3pandas
  - geoplot
  - pysal
  - scipy
  - opencv
  - imageio